# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANxMVyiZYPhA8hC2cqhGPCoPLnXcH1ah
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
st.markdown("""
<style>
body {
    background-color: #000000;
}
</style>
""", unsafe_allow_html=True)
import streamlit as st

# Usar una URL de la imagen como fondo
st.markdown(
    """
    <style>
    .reportview-container {
        background: url("https://github.com/BlackMeett/Solemne_3/blob/main/Business%20Event%20Website.png") no-repeat center center fixed;
        background-size: cover;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# El contenido de tu app
st.title('Mi Evento de Negocios')
st.write('Bienvenidos a mi página web del evento de negocios.')
















