# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANxMVyiZYPhA8hC2cqhGPCoPLnXcH1ah
"""
import streamlit as st
import base64

image_path = "fondo_morado.png"  

with open(image_path, "rb") as img_file:
    base64_image = base64.b64encode(img_file.read()).decode()


st.markdown(
    f"""
    <style>
    .stApp {{
        background-image: url("data:image/png;base64,{base64_image}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }}
    </style>
    """,
    unsafe_allow_html=True
)


import streamlit as st

# Configuración inicial para la página
if "page" not in st.session_state:
    st.session_state.page = "inicio"

# Título de la aplicación
st.title("Aplicación de Categorías")

# Mostrar botones solo si estamos en la página de inicio
if st.session_state.page == "inicio":
    st.header("Página Principal: Elige una Categoría")
    st.write("Selecciona una categoría para ver más detalles.")
    
    if st.button("Ir a Categoría 1"):
        st.session_state.page = "categoría_1"
    
    elif st.button("Ir a Categoría 2"):
        st.session_state.page = "categoría_2"
    
    elif st.button("Ir a Categoría 3"):
        st.session_state.page = "categoría_3"

# Mostrar contenido según la página seleccionada
if st.session_state.page == "categoría_1":
    st.header("Categoría 1: Información de la Categoría 1")
    st.write("Aquí va la información relacionada con la Categoría 1.")
    
    with st.form(key="form_cat1"):
        name = st.text_input("Ingresa tu nombre:")
        age = st.number_input("Ingresa tu edad:", min_value=1, max_value=100)
        submit_button = st.form_submit_button("Enviar")
    
    if submit_button:
        st.write(f"¡Hola {name}, tienes {age} años! Gracias por enviar el formulario.")
    
    if st.button("Volver atrás"):
        st.session_state.page = "inicio"

elif st.session_state.page == "categoría_2":
    st.header("Categoría 2: Información de la Categoría 2")
    st.write("Aquí va la información relacionada con la Categoría 2.")
    
    with st.form(key="form_cat2"):
        product = st.text_input("Ingresa el nombre del producto:")
        quantity = st.number_input("Ingresa la cantidad:", min_value=1)
        submit_button = st.form_submit_button("Enviar")
    
    if submit_button:
        st.write(f"Has ingresado el producto: {product} con cantidad: {quantity}. ¡Gracias!")
    
    if st.button("Volver atrás"):
        st.session_state.page = "inicio"

elif st.session_state.page == "categoría_3":
    st.header("Categoría 3: Información de la Categoría 3")
    st.write("Navegacion Libre")  
    if st.button("Volver atrás"):
        st.session_state.page = "inicio"













